In [1]:
import pandas as pd

In [ ]:
# 1. Leer el archivo crudo
ruta_original = r'C:\olist\olist_data\olist_geolocation_dataset.csv'
df = pd.read_csv(ruta_original)

In [3]:
# Ver la ventana alrededor del primer error (fila 421040 de SQL)
print("--- Sospechoso 1 ---")
display(df.iloc[421035 : 421042])

--- Sospechoso 1 ---

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
421035,21031,-22.849001,-43.260463,rio de janeiro,RJ
421036,21020,-22.831862,-43.269715,rio de janeiro,RJ
421037,21046,-22.866663,-43.234451,rio de janeiro,RJ
421038,21032,-22.857779,-43.252626,"rio de janeiro, rio de janeiro, brasil",RJ
421039,21020,-22.833671,-43.279603,rio de janeiro,RJ
421040,21050,-22.878171,-43.263891,rio de janeiro,RJ
421041,21040,-22.860133,-43.251607,rio de janeiro,RJ

In [4]:
# Ver la ventana alrededor del segundo error (fila 698308 de SQL)
print("\n--- Sospechoso 2 ---")
display(df.iloc[698305 : 698310])

--- Sospechoso 2 ---

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
698305,47200,-9.622779,-42.081474,remanso,BA
698306,47220,-9.517593,-43.014366,"campo alegre de lourdes, bahia, brasil",BA
698307,47200,-9.616500,-42.079535,remanso,BA
698308,47200,-9.617026,-42.075617,remanso,BA
698309,47240,-9.996058,-42.483693,pilao arcado,BA

In [5]:
# 2. Eliminar las comas traicioneras dentro de la columna de ciudad
# (Reemplazamos la coma por un espacio vacío)
df['geolocation_city'] = df['geolocation_city'].str.replace(',', ' -', regex=False)

In [6]:
# Comprobar datos cambiados
print("--- Ya no más comas incómodas ---")
display(df.iloc[421035 : 421042])
display(df.iloc[698305 : 698310])

--- Ya no más comas incómodas ---

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
421035,21031,-22.849001,-43.260463,rio de janeiro,RJ
421036,21020,-22.831862,-43.269715,rio de janeiro,RJ
421037,21046,-22.866663,-43.234451,rio de janeiro,RJ
421038,21032,-22.857779,-43.252626,rio de janeiro - rio de janeiro - brasil,RJ
421039,21020,-22.833671,-43.279603,rio de janeiro,RJ
421040,21050,-22.878171,-43.263891,rio de janeiro,RJ
421041,21040,-22.860133,-43.251607,rio de janeiro,RJ

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
698305,47200,-9.622779,-42.081474,remanso,BA
698306,47220,-9.517593,-43.014366,campo alegre de lourdes - bahia - brasil,BA
698307,47200,-9.616500,-42.079535,remanso,BA
698308,47200,-9.617026,-42.075617,remanso,BA
698309,47240,-9.996058,-42.483693,pilao arcado,BA

In [7]:
# 3. Guardar un nuevo archivo 100% limpio
ruta_limpia = r'C:\olist\olist_data\olist_geolocation_dataset_clean.csv'
df.to_csv(ruta_limpia, index=False)

print("¡Archivo limpiado y guardado con éxito!")

¡Archivo limpiado y guardado con éxito!